# Generated by Django 4.2.26 on 2025-11-25 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='category_name',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(default='Not Selected', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(default='Not Selected', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Not Specified', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.CharField(default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='upazila',
            field=models.CharField(default='Not Selected', max_length=100),
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2025),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(default='N/A', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_name',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='yearregistration',
            name='email',
            field=models.EmailField(default='not_provided@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='yearregistration',
            name='school_name',
            field=models.CharField(default='Not Provided', max_length=200),
        ),
        migrations.AlterField(
            model_name='yearregistration',
            name='student',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Registration.student'),
        ),
        migrations.AlterField(
            model_name='yearregistration',
            name='username',
            field=models.CharField(db_index=True, default='00000000', max_length=50),
        ),
        migrations.AlterField(
            model_name='yearregistration',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=2025),
        ),
    ]
