# Generated by Django 5.2.6 on 2025-11-28 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_remove_student_address_student_category_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YearRegistration',
            new_name='Year2025',
        ),
    ]
